categories:
- Proteomics
owner: galaxyp
homepage_url: http://proteowizard.sourceforge.net/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot

repositories:
  myrimatch:
    description: Bumbershoot MyriMatch
    long_description: |
      MyriMatch is a shotgun proteomics search engine for tandem mass spectra.
    include:
      - myrimatch.xml
      - macros.xml
      - test-data
  idpqonvert:
    description: Bumbershoot IDPicker idpQonvert
    long_description: |
      Q-value + convert = qonvert
      idpQonvert qonverts raw pepXML and mzIdentML files to IDPicker idpDB files.
    include:
      - idpqonvert.xml
      - idpQonvertEmbedder.xml
      - macros.xml
      - test-data
  idpassemble:
    description: Bumbershoot IDPicker idpAssemble
    long_description: |
      idpAssemble merges multiple idpDB files into a single idpDB. It can also filter the result at PSM/spectrum/peptide/protein/gene levels
    include:
      - idpassemble.xml
      - macros.xml
      - test-data
  idpassemble:
    description: Bumbershoot IDPicker idpQuery
    long_description: |
      idpQuery creates customizable text reports from idpDB files.
    include:
      - idpquery.xml
      - macros.xml
      - test-data