categories: [Proteomics]
description: Isobaric Quantitation using QuantWiz-IQ
long_description: |
    This is the Galaxy Wrapper for the QuantWiz-IQ:
    QuantWiz-IQ is a tool for reporter based MS/MS quantitation using iTRAQ or TMT tags from shotgun proteomics experiments.
    
name: quantwiz_iq
owner: galaxyp
homepage_url: https://sourceforge.net/projects/quantwiz/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/quantwiz_iq

