categories: !!python/tuple [Tool Dependency Packages]
description: 'Tool dependencies for SearchGUI 2.8'
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_searchgui_2_8'
name: 'package_searchgui_2_8'
owner: 'galaxyp'
