name: validate_fasta_database
owner: galaxyp
description: runs Compomics database identification tool on any FASTA database, and separates valid and invalid entries based on a series of checks.
type: unrestricted
categories: 
- "Fasta Manipulation"
- "Proteomics"
