categories:
    - Proteomics
description: The tool LabeledProteinQuantification aggregates 
long_description: |
    After quantification and protein inference are performed, it is known which peptide originated from which protein, as well as the intensity of each peptide. 
    The information available for each peptide now needs to be aggragated for their proteins. This tool performs the aggregation from the peptides to the protein in 
    several steps. The first step for the labeled protein quantification is the aggregation of the differently labeled peptides. Peptides with the same sequence, 
    modifications and charge are aggregated and the ratio between the intensity from the light and heavy version is calculated. The next two aggregation steps are 
    optional. One of them is the aggregation based on charge state. Similarily to the first step, peptides with the same sequence and modifications, but different 
    charge states are being aggregated. The next optional step does the same for peptides with the same sequence, but different modification. Those steps build upon 
    each other. The last step is the aggregation of all peptides of a protein. The result of each aggregation step is given as a tab separated file. 
    The aggregation is performed according to the given parameters for each step. If an optional aggregation is not performed, the next step takes the result from 
    the prior aggregation. For example, if aggregation by charge and modification are skipped, the protein aggregation gets a collection of peptides, where a 
    peptidesequence can occur with different charge states and midifications.
name: proteomiqon_labeledproteinquantification
owner: galaxyp
homepage_url: https://csbiology.github.io/ProteomIQon/tools/LabeledProteinQuantification.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteomiqon_labeledproteinquantification
type: unrestricted
