categories:
  - Proteomics
description: DiaNN (DIA-based Neural Networks) is a software for DIA/SWATH data processing.
long_description: |
  DiaNN (DIA-based Neural Networks) is a software for DIA/SWATH data processing. It can be used for both library-based and library-free analysis, and it supports all types of DIA/SWATH acquisitions.
homepage_url: https://github.com/vdemichev/DiaNN
name: diann
owner: galaxyp
remote_repository_url: https://github.com/vdemichev/DiaNN
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}"
