categories:
- Proteomics
description: diapysef is a convenience package for working with DIA-PASEF data
long_description: |
    A few scripts and modules for analysis of TIMS-TOF data.
name: diapysef
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/diapysef
homepage_url: https://pypi.org/project/diapysef/
type: unrestricted
