categories: [Proteomics]
description: "This tool computes the number of proteins from your list divided by the total number of protein of each KEGG pathway."
name: proteore_compute_kegg_pathways
owner: proteore
include:
 - compute_kegg_pathways.xml
 - compute_kegg_pathways.R
 - tool_data_table_conf.xml.sample
 - entrez_kegg_list.loc.sample
 - uniprot_kegg_list.loc.sample
 - test-data/SPZ.soluble.txt
 - tool-data/l.hsa.gene.RData
 - tool-data/l.hsa.up.RData
 - tool-data/l.mmu.gene.RData
 - tool-data/l.mmu.up.RData