categories: [Proteomics]
description: ProteoRE reactome
long_description: Query Reactome with your IDs list
name: proteore_reactome
owner: proteore
include:
  - README.rst
  - reactome_analysis.py
  - reactome_analysis.xml
  - template.html
  - test-data/ID_Converter_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/Reactome_Analysis_Tools_invalid_ID.txt
  - test-data/Reactome_Analysis_Tools.html