
            fastaFiles: [/tmp/tmpuhlzy3c0/files/3/d/3/dataset_3d3b3e3a-7402-4c0f-b7c7-8ff4c9948ac6.dat]
            parseRules:
              identifierParseRule: '^>.*\|(.*)\|.*$'
              descriptionParseRule: '^>.*\|.*\|[^ ]+ (.*) OS.*$'
            minUniquePeptides: 1
            minPepLen: 7
            maxPeptideMass: 4600
            calcPeakProperties: False
            writeMzTab: False
            ibaq: True
            ibaqLogFit: False
            separateLfq: False
            lfqStabilizeLargeRatios: True
            lfqRequireMsms: True
            advancedSiteIntensities: True
            matchBetweenRuns: False
            includeContaminants: True
            minPeptideLengthForUnspecificSearch: 8
            maxPeptideLengthForUnspecificSearch: 25
            decoyMode: revert
            peptideFdr: 0.01
            proteinFdr: 0.01
            quantMode: 1
            restrictProteinQuantification: True
            restrictMods: [Oxidation (M),Acetyl (Protein N-term)]
            useCounterparts: True
            paramGroups:
              - files: ['BSA_min_22.mzxml']
                maxMissedCleavages: 1
                fixedModifications: [Carbamidomethyl (C)]
                variableModifications: [Oxidation (M)]
                enzymes: [Trypsin/P]
                enzymeMode: 0
                lfqMode: 1
                lfqNormType: 1
                lfqMinEdgesPerNode: 3
                lfqAvEdgesPerNode: 6
                lfqMinRatioCount: 2
        