categories: [Proteomics]
description: "ProteoRE ID_Converter: A tool converts identifiers which are of a different type/source to another
  type of identifiers and create the identifier lists"
name: proteore_id_converter
owner: proteore
include:
  - README.rst
  - id_converter.xml
  - id_converter_UniProt.R
  - test-data/FKW_Lacombe_et_al_2017_OK.txt
  - test-data/ID_Converter_FKW_Lacombe_et_al_2017_OK.txt
  - tool-data/human_id_mapping_file.txt
