categories: [Proteomics]
description: "ProteoRE ID_Converter: A tool for converting public database identifiers"
name: proteore_id_converter
owner: proteore
include:
  - README.rst
  - id_converter.xml
  - id_converter.py
  - test-data/FKW_Lacombe_et_al_2017_OK.txt
  - test-data/ID_Converted_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/id_mapping_file.loc
  - test-data/human_id_mapping_file.tsv
  - test-data/mouse_id_mapping.tsv
  - tool-data/proteore_id_mapping_dictionaries.loc.sample
  - tool-data/human_id_mapping_04-01-2019.pickle
  - tool-data/mouse_id_mapping_04-01-2019.pickle
  - tool-data/rat_id_mapping_04-01-2019.pickle
  - tool_data_table_conf.xml.sample
  - tool_data_table_conf.xml.test