categories:
- Proteomics
description: moFF (a modest Feature Finder) extracts MS1 intensities from RAW and mzML spectrum files.  
long_description: |
    moFF is an open-source Python program for label-free quantification. It associates the apex intensity of the MS1 scans with peptides identified via SearchGUI/PeptideShaker or other search engine tools.
    https://github.com/compomics/moFF
name: proteomics_moff
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/moFF
homepage_url: https://github.com/compomics/moFF
type: unrestricted
