categories: [Proteomics]
description: Build tissue-specific expression dataset
long_description:
name: proteore_tissue_specific_expression_data
owner: proteore
include:
- Build_tissue-specific_expression_dataset.xml
- Build_tissue-specific_expression_dataset.R
- test-data/test.txt
- tool-data/HPA_full_atlas_23-10-2018.tsv
- tool-data/HPA_normal_tissue_23-10-2018.tsv
- tool-data/HPA_rna_tissue_23-10-2018.tsv
- proteore_protein_atlas_normal_tissue.loc.sample
- proteore_protein_atlas_rna_tissue.loc.sample
- tool_data_table_conf.xml.sample