categories: [Proteomics]
description: Build tissue-specific expression dataset
long_description:
name: proteore_retrieve_from_hpa
owner: proteore
include:
- Build_tissue-specific_expression_dataset.xml
- Build_tissue-specific_expression_dataset.R
- normal_tissue.tsv
- rna_tissue.tsv
- test-data/test.txt