owner: galaxyp
name: morpheus
categories:
- Proteomics
description: Morpheus MS Search Application
homepage_url: https://cwenger.github.io/Morpheus
long_description: |
  Morpheus database search algorithm for high-resolution tandem mass spectra.   

  Features automatic inclusion of known PTMs (Post Translational Modifications) 
  when a UniProt Proteome is used as the search database.

  https://github.com/cwenger/Morpheus/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/morpheus
type: unrestricted
