name: pepquery2
owner: galaxyp
categories: 
  - Proteomics
description: "PepQuery2 peptide-centric MS search for peptide identification and validation"
long_description: PepQuery2 is a peptide-centric mass spectromery search approach that focuses
  on peptide or protein sequences of interest. 
  PepQuery allows quick and easy proteomic validation of genomic alterations without
  customized database construction. 
homepage_url: https://pepquery.org
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pepquery2
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} (from the PepQuery2 tool suite)"
suite:
  name: "suite_pepquery2"
  description: PepQuery2 peptide-centric MS search for peptide identification and validation

