categories: [Proteomics]
description: ProteoRE clusterProfiler 
long_description: A tool performing GO terms classification and enrichment analysis using R package clusterProfiler
name: proteore_clusterprofiler
owner: proteore
include:
  - README.rst
  - cluster_profiler.xml
  - GO-enrich.R
  - test-data/Lacombe_et_al_2017_OK.txt
  - test-data/clusterProfiler_diagram_outputs__GGO.CC.png
  - test-data/clusterProfiler_text_output.tabular