categories: [Proteomics]
description: ProteoRE clusterProfiler 
long_description: A tool performing GO terms classification and enrichment analysis using R package clusterProfiler
name: proteore_clusterprofiler
owner: proteore
include:
  - README.rst
  - cluster_profiler.xml
  - GO-enrich.R
  - test-data/Lacombe_et_al_2017_OK.txt
  - test-data/background_ids.txt
  - test-data/cluster_profiler_EGO_BP.csv
  - test-data/cluster_profiler_EGO_CC.csv
  - test-data/cluster_profiler_EGO_MF.csv
  - test-data/cluster_profiler_GGO_BP.csv
  - test-data/cluster_profiler_GGO_CC.csv
  - test-data/cluster_profiler_GGO_MF.csv
  - test-data/EGO_BP_bar-plot
  - test-data/EGO_BP_dot-plot
  - test-data/EGO_CC_bar-plot
  - test-data/EGO_CC_dot-plot
  - test-data/GGO_BP_bar-plot
  - test-data/GGO_CC_bar-plot
  - test-data/GGO.CC.png
  - test-data/GGO_MF_bar-plot
  - test-data/input_id_list.csv
  - test-data/input_test.txt
  - test-data/log.txt
  - test-data/mouse_geneID.txt
  - test-data/universe.csv