categories: 
 - Proteomics
description: Uses positive and negative substrates to determine a kinase's preferred substrate motif
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp
long_description: Once the positive and negative substrates of a kinase are determined, this tool determines the kinase's preferred substrate motif, allowing for the creation of novel in vitro substrates
name: ktid_fisher_test
owner: galaxyp
remote_repository_url: https://github.umn.edu/blank121/Kinatest.R
