name: i2nca
owner: galaxyp
categories:
  - Proteomics
  - Imaging
description: i2nca is a preprocessing software for MSI data in imzML format.
long_description: |
  i2nca (msI INteractive Conversion and quality Assesment) is designed to utilize the imzml parsing capabilities of m2aia and provides internal file conversions within this file type.
  It can also perform multi-file operations and generate quality reports on imzML files.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/i2nca
homepage_url: https://github.com/cKNUSPeR/i2nca
