categories:
    - Proteomics
description: The tool ProteomIQon PeptideDB creates a peptide database in the SQLite format.
long_description: |
    MS-based shotgun proteomics estimates protein abundances using a proxy: peptides. 
    An established method to identify acquired MS/MS spectra is the comparison of each spectrum with peptides in a reference database. 
    The PeptideDB tool helps to create peptide databases by in silico digestion given proteome information in the FASTA format and a set of parameters that allow the user to mimic
    conditions of their specific experiment. The created database stores peptide protein relationships in a SQLite database which can then be supplied to other ProteomIQon tools.
name: proteomiqon_peptidedb
owner: galaxyp
homepage_url: https://csbiology.github.io/ProteomIQon/tools/PeptideDB.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteomiqon_peptidedb
type: unrestricted
