categories:
    - Proteomics
description: "MS-based shotgun proteomics estimates protein abundances using a proxy: peptides. The process of 'Protein Inference' is concerned with the mapping of identified peptides to the proteins they putatively originated from."
long_description: |
    MS-based shotgun proteomics estimates protein abundances using a proxy: peptides. 
    The process of 'Protein Inference' is concerned with the mapping of identified peptides to the proteins they putatively originated from. 
    This process is not as straightforward as one might think at a first glance on the subject, since the peptide-to-protein mapping is not necessarily a one-to-one relationship but in many cases a
    one-to-many relationship. This is due to the fact that many proteins share peptides with an identical sequence, e.g. two proteins originating from two different splice variants of the same gene.
    The ProteinInference tool relies on the concepts of protein groups and peptide evidence classes.
name: proteomiqon_proteininference
owner: galaxyp
homepage_url: https://csbiology.github.io/ProteomIQon/tools/ProteinInference.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteomiqon_proteininference
type: unrestricted
