categories: [Proteomics]
description: ProteoRE venn_diagram
long_description: Compare lists plotting Venn Diagram (based on Jvenn)
name: proteore_venn_diagram
owner: proteore
include:
  - README.rst
  - venn_diagram.py
  - venn_diagram.xml
  - jvenn_template.html
  - test-data/ID_Converter_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/Mucilli.txt
  - test-data/Bredberg.txt
  - test-data/Venn_diagram_html.html
  - test-data/Venn_text_output.txt