 This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details
language: python

env:
  - TESTFOLDER=tools/filter_keywords_values
  # - TESTFOLDER=tools/xcms_xcmsset
  # - TESTFOLDER=tools/xcms_merge
  # - TESTFOLDER=tools/xcms_group
  # - TESTFOLDER=tools/xcms_retcor
  # - TESTFOLDER=tools/xcms_fillpeaks
  # - TESTFOLDER=tools/xcms_plot_chromatogram
  # - TESTFOLDER=tools/xcms_summary

before_install:
  - sudo apt-get install -y python-virtualenv
  - virtualenv planemo-venv
  - . planemo-venv/bin/activate
  - pip install planemo==0.58.1


script:
  - planemo lint ${TRAVIS_BUILD_DIR}/${TESTFOLDER}
  - planemo test  --galaxy_branch release_19.01 ${TRAVIS_BUILD_DIR}/${TESTFOLDER}