name: pepquery
owner: galaxyp
categories: 
  - Proteomics
description: "A peptide-centric MS search engine for novel peptide identification and validation."
long_description: PepQuery is a peptide-centric mass spectromery search approach that focuses
  on only novel DNA or protein sequences of interest. 
  PepQuery allows quick and easy proteomic validation of genomic alterations without
  customized database construction. 
homepage_url: https://pepquery.org
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pepquery
