categories: 
  - Proteomics
description: "A peptide-centric search engine for novel peptide identification and validation."
name: pepquery
owner: rsajulga
homepage_url: https://pepquery.org
remote_repository_url: https://github.com/jraysajulga/pepquery-wrapper
