# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db_annotation_data_manager
categories:
- Proteomics
owner: galaxyp
name: custom_pro_db_annotation_data_manager
description: CustomProDB Annotation
long_description: |
  Retrieves annotation for a given UCSC dbKey and creates annotation suitable for input to customProDB and proBAMr.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot/custom_pro_db
homepage_url: https://bioconductor.org/packages/release/bioc/html/customProDB.html