categories:
  - Proteomics
description: Converts coordinates from a tabular file into a formatted text file readable by Zeiss laser-capture microdissection systems
long_description: |
   This tool is part of a workflow that allows to use tissue anontations in geojson format from machine learning based imaging software like QuPath and HaloAI and transform these annotation coordinates into a text format readable by Zeiss laser-capture microdissection systems
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/zeiss_lmd_converter
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/zeiss_lmd_converter
type: unrestricted
