owner: galaxyp
name: meta_proteome_analyzer
categories:
- Proteomics
description: MetaProteomeAnalyzer
long_description: |
  MPA Portable is a light-weight and stand-alone software for the identification of proteins 
  and in-depth analysis of metaproteomics (and also proteomics) data. 
  The MPA software currently supports the database search engines Comet, MS-GF+ and X!Tandem 
  taking MGF spectrum files as input data. User-provided FASTA databases 
  (preferably downloaded from UniProtKB) are formatted automatically. 

  https://github.com/compomics/meta-proteome-analyzer/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/meta_proteome_analyzer
homepage_url: https://github.com/compomics/meta-proteome-analyzer/
type: unrestricted
