categories: [Proteomics]
description: ProteoRE Add protein features (Mouse)
long_description: A tool for adding biochemical and cellular annotation to your protein list from UniProt
name: proteore_prot_features_mouse
owner: proteore
include:
  - README.rst
  - add_protein_features_mouse.xml
  - add_protein_features_mouse.R
  - tool-data/uniprot_features_mouse.tsv
  - test-data/Wilson-foie-souris-up.txt
  - test-data/results_wilson-foie-souris-up.tsv