categories: 
 - Proteomics
description: Discovers which tyrosine containing peptides *could* have been phosphorylated, but were not
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp
long_description: To determine a kinase's preferred substrate motif, it is necessary to know not just what it will phosphorylate, but what it wil not phosphorylate.
    This tool discovers what peptides were present in the kinase experiment and could have been phosphorylated but were not found phosphorylated by the mass spec
  
name: negative_motif_finder
owner: galaxyp
remote_repository_url: https://github.umn.edu/blank121/Negative-Motif-Finder-GalaxyP
