owner: galaxyp
name: mz_to_sqlite
categories:
- Proteomics
description: Creates a SQLite database for proteomics data
long_description: |
  Extract proteomics files: mzIdentML, mzML, MGF, fasta, uniprot_xml into a SQLite DB
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/mz_to_sqlite
type: unrestricted
homepage_url: https://github.com/galaxyproteomics/mzToSQLite
