categories: [Proteomics]
description: find pathways related to uniprot.AC or geneID 
name: proteore_find_pathways
owner: proteore
include:
 - find_pathways.xml
 - keggrest.R
 - tool_data_table_conf.xml.sample
 - entrez_kegg_list.loc.sample
 - uniprot_kegg_list.loc.sample
 - test-data/SPZ.soluble.txt
 - tool_data/l.hsa.gene.RData
 - tool_data/l.hsa.up.RData
 - tool_data/l.mmu.gene.RData
 - tool_data/l.mmu.up.RData