categories:
    - Proteomics
description: The tool JoinQuantPepIonsWithProteins combines results from ProteinInference and PSMBasedQuantification.
long_description: |
    Results from PSMBasedQuantification contain detailed information about the quantification of every peptide, but only basic informations about the protein they 
    originated from. This information is obtained during the ProteinInference. This tool takes the results from both tools and combines the quantification 
    information of each peptide with the more accurate information about the corresponding protein including its q-value.
name: proteomiqon_joinquantpepionswithproteins
owner: galaxyp
homepage_url: https://csbiology.github.io/ProteomIQon/tools/JoinQuantPepIonsWithProteins.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteomiqon_joinquantpepionswithproteins
type: unrestricted
