owner: galaxyp
name: psm_zscore
categories:
- Proteomics
description: Calculate Z scores for PSMs ( Peptide Spectral Matches )
long_description: |
  Calculate Z scores for PSMs ( Peptide Spectral Matches )
 
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/psm_zscore
type: unrestricted
