owner: galaxyp
name: fragpipe
categories:
- Proteomics
description: Data analysis for mass spectrometry-based proteomics.
homepage_url: https://fragpipe.nesvilab.org/
long_description: |
  FragPipe is a suite of computational tools enabling comprehensive analysis of mass spectrometry-based proteomics data.
  FragPipe uses MSFragger - an ultrafast proteomic search engine suitable for both conventional and “open” (wide precursor mass tolerance) peptide identification.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/fragpipe
type: unrestricted
