categories: [Proteomics]
description: ProteoRE Add protein features (Human, Mouse, Rat)
long_description: A tool for adding biochemical and cellular annotation to your protein list from UniProt
name: proteore_prot_features_3orga
owner: galaxyp
