owner: galaxyp
name: metanovo
categories:
- Proteomics
description: Produce targeted databases for mass spectrometry analysis.
homepage_url: https://github.com/uct-cbio/proteomics-pipelines
long_description: |
  MetaNovo combines existing tools with a custom algorithm to create a pipeline
  for searching MS/MS data against a FASTA database of known proteins,
  producing an output database of matching proteins.

  https://www.biorxiv.org/content/10.1101/605550v7
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/metanovo
type: unrestricted
