# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db
categories:
- Proteomics
owner: galaxyp
name: custom_pro_db
description: CustomProDB
long_description: |
  CustomProDB creates custom protein databases based on transcriptome/exosome expression (BAM files), including variants from SNPs, INDELs, and novel junctions (VCF files).
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot/custom_pro_db
homepage_url: https://bioconductor.org/packages/release/bioc/html/customProDB.html