name: gffcompare_to_bed
owner: galaxyp
categories: [Convert Formats]
description: Filter and convert a gffCompare GTF to BED
long_description: |
  Converts the annotated GTF output from gffCompare to BED format.
  The GTF can be filtered using the class_code annotations from gffCompare.
homepage_url: https://github.com/gpertea/gffcompare/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/gffcompare_to_bed
