owner: galaxyp
name: thermo_raw_file_converter
categories:
- Proteomics
description: Thermo RAW file converter
long_description: |
    Thermo RAW file converter based on the great ThermoRawFileParser project.
homepage_url: https://github.com/compomics/ThermoRawFileParser
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/ThermoRawfileParser
type: unrestricted
