owner: galaxyp
name: package_peptideshaker_0_38
categories:
- Tool Dependency Packages
description: PeptideShaker and SearchGUI 0.38
long_description: |
  Runs multiple search engines (X! Tandem, OMSSA and MS-GF+) on any number of MGF peak lists using the SearchGUI application and combines the results.

  https://code.google.com/p/peptide-shaker/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_peptideshaker_0_38
type: unrestricted
