owner: galaxyp
name: cravatool
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/cravatp_score_and_annotate
description: This tool submits variant information to CRAVAT for pathological predictive scoring and
  comprehensive annotation. Proteogenomic inputs (proBED) are supported. These outputs can be visualized
  through the CRAVAT-Galaxy visualization plugin.
long_description: |
  This tool extends from In Silico's initial Toolshed commit (d26088c17c78) to support additional inputs:
   > human reference genome build (GRCh38 or GRCh37)
   > proteogenomic input (proBED) for intersection with genomic input (VCF)
      > whether to submit only intersected variants
      > whether to output the intersected VCF file
type: unrestricted
categories:
  - Proteomics
  - Variant Analysis