name: diffacto
owner: galaxyp
categories:
- Proteomics
type: unrestricted
description: Diffacto comparative protein abundance estimation
long_description: |
    Diffacto estimates comparative protein abundance from the covariation of peptide abundances.

homepage_url: https://github.com/statisticalbiotechnology/diffacto
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/diffacto
