categories:
  - Imaging
name: qupath_roi_splitter
owner: galaxyp
description: Split ROI coordinates of QuPath TMA annotation by cell type
homepage_url: https://github.com/npinter/ROIsplitter
remote_repository_url: hhttps://github.com/npinter/ROIsplitter
type: unrestricted
long_description: |
  This Galaxy tool extracts ROI coordinates of QuPath TMA annotation by cell type.
  It takes a collection containing GeoJSON files with QuPath annotation data as input and generates
  a list of text files containing the ROI coordinates for each cell type.
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"