name: mqppep
owner: galaxyp
description: MaxQuant Phosphoproteomic Enrichment Pipeline - Preprocessing and ANOVA
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/'
long_description: |
  Phosphoproteomic Enrichment Pipeline provides tools two tools for processing MaxQuant data for phosphoproteome-enriched samples.
 
  "MaxQuant Phosphopeptide Preprocessing" (mqppep_preproc) transforms the 'Phospho (STY)Sites.txt' output file that MaxQuant produces for for phosphoproteome-enriched samples to prepare it for ANOVA.

  "MaxQuant Phosphopeptide ANOVA" (mqppep_anova) performs ANOVA on the preprocessed data.

remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/mqppep
type: unrestricted
categories:
- Proteomics

suite:
  name: "suite_mqppep"
  description: suite for preprocessing, ANOVA, and KSEA of MaxQuant results for phosphoproteomic enrichment
  long_description: |
    Phosphoproteomic Enrichment Pipeline provides tools for preprocessing
    the 'Phospho (ST)Sites.txt' or 'Phospho (Y)Sites.txt' files produced
    by MaxQuant and for ANOVA analysis of the preprocessed data.

repositories:
  mqppep_preproc:
    description: "Prep phosphoproteomic MaxQuant output for statistical anlaysis."
  mqppep_anova:
    description: "Run ANOVA and KSEA for phosphopeptides."
