categories:
    - Proteomics
description: The tool LabelFreeProteinQuantification estimates protein abundances using quantified peptide ions. 
long_description: |
    After quantification and protein inference are performed, it is known which peptide originated from which protein, as well as the intensity of each peptide. 
    The information available for each peptide now needs to be aggragated for their proteins.
    This tool performs the aggregation from the peptides to the protein in several steps. The first two aggregation steps are optional. One of them is the aggregation based on 
    charge state. Peptides with the same sequence and modifications, but different charge states are being aggregated. 
    The next optional step does the same for peptides with the same sequence, but different modifications. Those steps build upon each other. 
    The last step is the aggregation of all peptides of a protein. The result of each aggregation step is given as a tab separated file. The aggregation is performed according to 
    the given parameters for each step. If an optional aggregation is not performed, the next step takes the result from the prior aggregation. For example, if aggregation by charge 
    and modification are skipped, the protein aggregation is performed on previously unaggregated peptides, where a peptidesequence can occur with different charge states and 
    modifications.
name: proteomiqon_labelfreeproteinquantification
owner: galaxyp
homepage_url: https://csbiology.github.io/ProteomIQon/tools/LabelfreeProteinQuantification.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteomiqon_labelfreeproteinquantification
type: unrestricted
