name: retrieve_ensembl_bed
owner: galaxyp
categories: [Data Source]
description: Retrieve cDNA features from Ensembl REST API in BED format
long_description: |
  Retrieve cDNA features from Ensembl REST API in BED format.
  Features can be filtered by genomic region or Ensembl biotype.
homepage_url: http://rest.ensembl.org/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteogenomics/retrieve_ensembl_bed
