categories: [Proteomics]
description: Get MS/MS observations in a tissue/fluid from Peptide Atlas
name: proteore_ms_observation_pepatlas
owner: proteore
include:
  - Get_ms-ms_observations.R
  - Get_ms-ms_observations.xml
  - proteore_peptide_atlas.loc.sample
  - tool_data_table_conf.xml.sample
  - tool_data_table_conf.xml.test
  - README.rst
  - test-data/FKW_Lacombe_et_al_2017_OK.txt
  - test-data/Human_Brain_25-07-2018.tsv
  - test-data/Human_CSF_25-07-2018.tsv
  - test-data/Human_Heart_25-07-2018.tsv
  - test-data/Human_Kidney_25-07-2018.tsv
  - test-data/Human_Liver_25-07-2018.tsv
  - test-data/Human_Plasma_25-07-2018.tsv
  - test-data/Human_Urine_25-07-2018.tsv
  - test-data/PeptideAtlas_output.txt
  - tool-data/Human_Adrenal_gland_2014-08.tsv
  - tool-data/Human_Brain_2015-01.tsv
  - tool-data/Human_Breast_2014-08.tsv
  - tool-data/Human_Colon_cancer_2013-02.tsv
  - tool-data/Human_CSF_2014-09.tsv
  - tool-data/Human_Digestive_system_2014-08.tsv
  - tool-data/Human_Female_reproductive_system_2014-08.tsv
  - tool-data/Human_Heart_2014-08.tsv
  - tool-data/Human_Kidney_2014-08.tsv
  - tool-data/Human_Liver_2014-08.tsv
  - tool-data/Human_Lung_2014-08.tsv
  - tool-data/Human_Male_reproductive_system_2014-08.tsv
  - tool-data/Human_Pancreas_2014-08.tsv
  - tool-data/Human_Plasma_non_glyco_2017-04.tsv
  - tool-data/Human_Spleen_2014-08.tsv
  - tool-data/Human_Testis_2017-01.tsv
  - tool-data/Human_Urinary_bladder_2014-08.tsv
  - tool-data/Human_Urine_2014-08.tsv