categories: [Proteomics]
description: Get MS/MS observations in a tissue/fluid from Peptide Atlas
name: proteore_ms_observation_pepatlas
owner: proteore
include:
  - Get_ms-ms_observations.R
  - Get_ms-ms_observations.xml
  - peptide_atlas.loc.sample
  - tool_data_table_conf.xml.sample
  - tool_data_table_conf.xml.test
  - README.rst
  - test-data/FKW_Lacombe_et_al_2017_OK.txt
  - test-data/Human_Brain_25-07-2018.tsv
  - test-data/Human_CSF_25-07-2018.tsv
  - test-data/Human_Heart_25-07-2018.tsv
  - test-data/Human_Kidney_25-07-2018.tsv
  - test-data/Human_Liver_25-07-2018.tsv
  - test-data/Human_Plasma_25-07-2018.tsv
  - test-data/Human_Urine_25-07-2018.tsv
  - test-data/PeptideAtlas_output.txt