# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/msconvert
categories:
  - Proteomics
description: ProteoWizard msconvert
long_description: |
  ProteoWizard msconvert can convert and filter mass spectrometry files. There is a no-vendor-support version that can run on Linux, and a vendor-support version that will only work on Windows.

  https://sourceforge.net/p/proteowizard/code/HEAD/tree/trunk/pwiz/pwiz_tools/commandline/
owner: galaxyp
name: msconvert
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/msconvert