# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/msconvert
owner: galaxyp
name: msconvert
categories:
- Proteomics
description: msconvert Convert and/or filter mass spectrometry files (including vendor formats) using the official Docker container
long_description: |
  Proteowizard msconvert
  Convert and/or filter mass spectrometry files using the offical Docker container.
  Using the Docker container requires agreeing to each vendor's license (for using their proprietary data access libraries): http://www.proteowizard.org/licenses.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msconvert
homepage_url: http://www.proteowizard.org
type: unrestricted

