# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/blast_plus_remote_blastp
owner: galaxyp
name: blast_plus_remote_blastp
homepage_url: https://blast.ncbi.nlm.nih.gov/
remote_repository_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/ncbi_blast_plus
description: NCBI BLAST+ with -remote option 
long_description: |
  The NCBI BLAST+ blastp tool find regions of similarity between biological sequences.
  This tool contains the blastp -remote and -entrez_query options to perform 
  species specific blastp queries at NCBI.  
  The query should be limited to a few hundred sequences.
categories:
- Sequence Analysis
type: unrestricted

