owner: galaxyp
name: feature_alignment
categories:
- Proteomics
description: TRIC integrates information from all available runs via a graph-based alignment strategy
long_description: |
 TRIC uses a graph-based alignment strategy based on non-linear retention time correction to integrate information from all available runs.

  https://github.com/msproteomicstools/msproteomicstools/blob/master/TRIC-README.md
remote_repository_url: https://github.com/msproteomicstools/msproteomicstools/blob/master/TRIC-README.md
type: unrestricted
