name: translate_bed
owner: galaxyp
categories: [Proteomics]
description: Translate BED transcript CDS or cDNA in 3 frames
long_description: |
  Translate transcripts from the input BED file into protein sequences.

  The genomic sequence may be supplied
  in an extra column in the BED input file,
  retrieved from a twobit genomic reference file,  
  or retrieved from the Ensembl REST API for Ensembl transcripts.

homepage_url: http://rest.ensembl.org/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteogenomics/translate_bed
