# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/pyprophet
categories:
  - Proteomics
description: Quality control reports for MaxQuant results
long_description: |
    Quality control reports for MaxQuant results
name: ptxqc
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/ptxqc
homepage_url: https://github.com/cbielow/PTXQC
type: unrestricted