owner: galaxyp
name: maxquant
categories:
- Proteomics
description: wrapper for MaxQuant
homepage_url: https://www.maxquant.org/
long_description: |
  MaxQuant is a quantitative proteomics software package
  designed for analyzing large mass-spectrometric data sets.

  It is specifically aimed at high-resolution MS data.
  Several labeling techniques as well as label-free quantification are supported.

  https://maxquant.org/

remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/maxquant
type: unrestricted
