categories:
  - Data Managers
description: data manager to download and set necessary files for "Number of MS/MS
  observations in a tissue (from Peptide Atlas)" and "Get expression data by tissue
  finds tissue" from the proteore package
name: proteore_data_manager
owner: proteore
include: 
  - data_manager/resource_building.py  
  - data_manager/resource_building.xml
  - tool-data/proteore_biogrid_dictionaries.loc.sample
  - tool-data/proteore_bioplex_dictionaries.loc.sample
  - tool-data/proteore_humap_dictionaries.loc.sample
  - tool-data/proteore_id_mapping_Human.loc.sample
  - tool-data/proteore_id_mapping_Mouse.loc.sample
  - tool-data/proteore_id_mapping_Rat.loc.sample
  - tool-data/proteore_protein_atlas_normal_tissue.loc.sample
  - tool-data/proteore_protein_atlas_rna_tissue.loc.sample
  - tool-data/proteore_protein_atlas_tumor_tissue.loc.sample
  - tool-data/proteore_protein_full_atlas.loc.sample
  - tool-data/proteore_nextprot_ref.loc.sample
  - tool-data/proteore_peptide_atlas.loc.sample
  - data_manager_conf.xml
  - tool_data_table_conf.xml.sample