categories: [Proteomics]
description: ProteoRE Add expression data to your protein list (mRNA and protein level data from Human Protein Atlas)
name: proteore_expression_rnaseq_abbased
owner: proteore
include:
  - README.rst
  - add_expression_HPA.R
  - add_expression_data.xml
  - test-data/ID_Converter_Lacombe_et_al_2017_OK.txt
  - test-data/Get_annotation_RNAseq.txt
  - tool-data/HPA_full_atlas_23-10-2018.tsv
  - proteore_protein_full_atlas.loc.sample
  - tool_data_table_conf.xml.sample
