name: masspix
categories: 
 - Metabolomics
 - Lipidomics
 - Mass Spectrometry Image Processing
description: Processes high resolution mass spectrometry imaging data
long_description:  |
  Processes high resolution mass spectrometry imaging data, performs
  multivariate statistics (PCA, clustering) and lipid identification.
owner: galaxyp
homepage_url: https://github.com/wanchanglin/massPix
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/masspix
type: unrestricted

