categories:
    - Proteomics
description: Validate PSM from Ion Fragmentation
homepage_url: https://github.com/galaxyproteomics/psm_fragments.git
long_description: PSM validation by comparing against peptide ion fragmentation
name: psm_validation
owner: galaxyp
remote_repository_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/psm_validation'
type: unrestricted
