categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads the ProteoWizard tools.
long_description: |
  ProteoWizard

  https://sourceforge.net/p/proteowizard/code/HEAD/tree/trunk/pwiz/
name: package_proteowizard_3_0_9016
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/packages/package_proteowizard_3_0_9016/
owner: galaxyp
type: tool_dependency_definition
