# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/pyprophet
categories:
  - Proteomics
description: Semi-supervised learning and scoring of OpenSWATH results.
long_description: |
    PyProphet is a Python re-implementation of the mProphet algorithm optimized for SWATH-MS data acquired by data-independent acquisition (DIA). The originally published algorithm been extended to support new data types and analysis modes.
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pyprophet
homepage_url: https://github.com/PyProphet/pyprophet
type: unrestricted
auto_tool_repositories:
    name_template: "{{ tool_id }}"
    description_template: "PyProphet suite: {{ tool_name }}"
suite:
    name: "suite_pyprophet"
    description: Semi-supervised learning and scoring of OpenSWATH results.
    long_description:
        PyProphet is a Python re-implementation of the mProphet algorithm optimized for SWATH-MS data acquired by data-independent acquisition (DIA). The originally published algorithm been extended to support new data types and analysis modes.
