categories: 
 - Proteomics
description: Allows the in silico generation and screening of novel kinase substrates
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp
long_description: 'Once a kinase's preferred substrate motif is determined, this tool allows the generation of novel substrates based on the kinase's preference, or the determination of if a specific substrate will be phosphorylated by the kinase of interest
  '
name: kinatest scoring function
owner: galaxyp
remote_repository_url: https://github.umn.edu/blank121/Kinatest.R
