categories:
- Proteomics
description: Protein Database Downloader
long_description: |
  Creates a FASTA file of specified protein sequences for comparison with experimental MS/MS data in search algorithm. 
name: dbbuilder
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/dbbuilder
homepage_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/dbbuilder
type: unrestricted
