owner: galaxyp
name: data_manager_eggnog_mapper
categories:
- Proteomics
description: downloads eggnog data for eggnog-mapper
long_description: |
  eggnog-mapper is a tool for fast functional annotation of novel sequences
  (genes or proteins) using precomputed eggNOG-based orthology assignments

  This installs eggnog data to directory relative to 
  the galaxy_data_manager_data_path declared in config/galaxy.yml

  https://github.com/jhcepas/eggnog-mapper
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/eggnog_mapper/eggnog_mapper_data_manager
type: unrestricted
