categories: !!python/tuple [Tool Dependency Packages]
description: 'Tool dependencies for SearchGUI 1.28'
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_searchgui_1_28'
name: 'package_searchgui_1_28'
owner: 'iracooke'
