categories: [Tool Dependency Packages]
description: 'Tool dependencies for PeptideShaker 1.11'
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_peptideshaker_1_11'
name: 'package_peptideshaker_1_11'
owner: 'galaxyp'
