categories: [Proteomics]
description: Build protein interaction maps
name: proteore_build_protein_interaction_maps
owner: proteore
include:
  - build_protein_interaction_maps.py
  - build_protein_interaction_maps.xml
  - tool_data_table_conf.xml.sample
  - tool_data_table_conf.xml.test
  - proteore_humap_dictionaries.loc.sample
  - proteore_bioplex_dictionaries.loc.sample
  - proteore_biogrid_dictionaries.loc.sample
  - tool-data/Human_biogrid_2019-03-01
  - tool-data/Human_bioplex_2019-03-01
  - tool-data/Human_humap_2019-03-01
  - tool-data/Mouse_biogrid_2019-03-01
  - tool-data/Rat_biogrid_2019-03-01
  - Lacombe_geneID.tsv
  - test-data/Network_biogrid_from_Lacombe_geneID.tsv
  - test-data/Network_biogrid_from_Rattus_Hameza_dataset_geneID.tsv
  - test-data/Network_biogrid_from_Wilson-foie-souris_geneID.tsv
  - test-data/Network_bioplex_from_Lacombe_geneID.tsv
  - test-data/Network_humap_from_Lacombe_geneID.tsv
  - test-data/Nodes_biogrid_from_Lacombe_geneID.tsv
  - test-data/Nodes_biogrid_from_Rattus_Hameza_dataset_geneID.tsv
  - test-data/Nodes_biogrid_from_Wilson-foie-souris_geneID.tsv
  - test-data/Nodes_bioplex_from_Lacombe_geneID.tsv
  - test-data/Nodes_humap_from_Lacombe_geneID.tsv
  - test-data/Rattus_Hameza_dataset_geneID.tsv
  - test-data/Wilson-foie-souris-up_geneID.tsv
  - test-data/cached_locally/proteore_biogrid_dictionaries.loc
  - test-data/cached_locally/proteore_bioplex_dictionaries.loc
  - test-data/cached_locally/proteore_humap_dictionaries.loc