categories: [Proteomics]
description: Build protein interaction maps
name: proteore_protein_interaction_maps
owner: proteore
include:
  - build_protein_interaction_maps.py
  - build_protein_interaction_maps.xml
  - tool_data_table_conf.xml.sample
  - proteore_humap_dictionaries.loc.sample
  - proteore_bioplex_dictionaries.loc.sample
  - proteore_biogrid_dictionaries.loc.sample
  - tool-data/Human_biogrid_01-03-2019.json
  - tool-data/Human_bioplex_01-03-2019.json
  - tool-data/Human_humap_01-03-2019.json
  - tool-data/Mouse_biogrid_01-03-2019.json
  - tool-data/Rat_biogrid_01-03-2019.json