categories: [Proteomics]
description: Build protein interaction maps
name: proteore_build_protein_interaction_maps
owner: proteore
include:
  - build_protein_interaction_maps.py
  - build_protein_interaction_maps.xml
  - tool_data_table_conf.xml.sample
  - proteore_humap_dictionaries.loc.sample
  - proteore_bioplex_dictionaries.loc.sample
  - proteore_biogrid_dictionaries.loc.sample
  - tool-data/Human_biogrid_2019-03-01.json
  - tool-data/Human_bioplex_2019-03-01.json
  - tool-data/Human_humap_2019-03-01.json
  - tool-data/Mouse_biogrid_2019-03-01.json
  - tool-data/Rat_biogrid_2019-03-01.json