owner: galaxyp
name: maxquant_mqpar
categories:
- Proteomics
description: wrapper for MaxQuant
long_description: |
  MaxQuant is a quantitative proteomics software package
  designed for analyzing large mass-spectrometric data sets.

  It is specifically aimed at high-resolution MS data.
  This wrapper serves as a workaround for not (yet) implemented
  features in the maxquant tool. It loads its parameters from a
  mqpar.xml file.

  https://maxquant.org/

remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/maxquant
type: unrestricted
