categories:
- Proteomics
description: ABRF2017 Metaproteomic Workshop Workflows
long_description: |
  Workflows for metaproteome taxonomic and functional analysis

Typical workflow:  
name: abrf2017_workshop
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/workflows/abrf2017_workshop
type: unrestricted
