owner: galaxyp
name: spectrast
categories:
- Proteomics
description: SpectraST can create, filter and search spectral libraries
long_description: |
  SpectraST is a spectral library creation and search tool developed at the ISB

  http://tools.proteomecenter.org/wiki/index.php?title=Software:SpectraST
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/spectrast
type: unrestricted
