categories:
- Metabolomics
description: Metabolite Database Downloader
long_description: |
  Creates a metabolite database file of the requested database in the requested format. 
name: dbbuilder_metabolites
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/dbbuilder_metabolites
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/dbbuilder_metabolites
type: unrestricted
