categories: [Proteomics]
description: ProteoRE Add protein features (Human, Mouse, Rat)
long_description: A tool for adding biochemical and cellular annotation to your protein list from UniProt
name: proteore_prot_features_3orga
owner: proteore
include:
  - add_protein_features_3orga.xml
  - add_protein_features_3orga.R
  - tool-data/uniprot_features_mouse-OK.tsv
  - tool-data/uniprot_features_human-OK.tsv
  - tool-data/uniprot_features_rat-OK.tsv
  - test-data/Wilson-foie-souris-up.txt
  - test-data/results_wilson-foie-souris-up.tsv
