categories: [Proteomics]
description: ProteoRE Expression levels by tissue
long_description: A tool for selecting and/or annotating a list of ENSG IDs with tissue expression
name: proteore_expression_levels_by_tissue
owner: proteore
include:
  - README.rst
  - sel_ann_hpa.R
  - sel_ann_hpa.xml
  - tool_data_table_conf.xml.sample
  - tool-data/proteinatlas.loc.sample
  - test-data/ID_Converter_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/normal_tissue.tsv
  - test-data/pathology.tsv