categories: [Data Source, Sequence Analysis]
description: Predict binding of peptides to any MHC or MHC II molecule of known sequence using artificial neural networks
homepage_url: http://tools.immuneepitope.org/main/tools-api/
long_description: The NetMHCpan and NetMHCiipan tools can now be accessed via the Next-Generation
  IEDB RESTful (REpresentational State Transfer) Web Services.
name: iedb_netmhcpan
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/iedb_netmhcpan
