categories: [Proteomics]
description: ProteoRE topGO
long_description: A tool performing enrichment analysis for Gene Ontology
name: proteore_topgo
owner: proteore
include:
  - README.rst
  - topGO.xml
  - topGO_enrichment.R
  - test-data/ID_Converter_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/barplot.png
  - test-data/dotplot.png
  - test-data/result.tsv
