categories: [Proteomics]
description: ProteoRE topGO
long_description: A tool performing enrichment analysis for Gene Ontology using R package topGO
name: proteore_topgo
owner: proteore
include:
  - README.rst
  - topGO.xml
  - enrichment_v3.R
  - test-data/ID_Converter_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/Barplot_output_for_topGO_analysis_BP_category.png
  - test-data/Dotplot_output_for_topGO_analysis_BP_category.png
  - test-data/Text_output_for_topGO_analysis_BP_category.tabular
