categories: [Proteomics]
description: FlashLFQ mass-spectrometry proteomics label-free quantification
homepage_url: https://github.com/smith-chem-wisc/FlashLFQ
long_description: FlashLFQ is an ultrafast label-free quantification algorithm for
  mass-spectrometry proteomics
name: flashlfq
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/flashlfq
