# repository published to https://toolshed.g2.bx.psu.edu/repos/galaxyp/psm_to_sam
categories:
- Proteomics
owner: galaxyp
name: psm_to_sam
description: PSM to SAM
long_description: |
  The interpretation of proteomics data is significantly enhanced by genomic annotation. 
  Using proBAMr, peptide-spectrum-matches can be easily reannotated using user-specified gene annotation 
  schemes and assembled into both protein and gene identifications. Using the genome as a common reference, 
  proBAMr facilitates seamless proteomics and proteogenomics data integration. ProBAM files can be readily 
  visualized in genome browsers and thus bring proteomics data analysis to a general audience beyond the 
  proteomics community.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/bumbershoot/psm2sam
homepage_url: https://bioconductor.org/packages/release/bioc/html/proBAMr.html