name: pmd_fdr
owner: galaxyp
categories:
- Proteomics
description: Calculate Precursor Mass Discrepancy (PMD) for MS/MS
long_description: |
  Calculate Precursor Mass Discrepancy for MS/MS PSMs ( Peptide Spectral Matches )

homepage_url: https://github.com/slhubler/PMD-FDR-for-Galaxy-P
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pmd_fdr
type: unrestricted
