categories:
- Proteomics
description: DIA-Umpire analysis for data independent acquisition (DIA) mass spectrometry-based proteomics
long_description: |
  DIA-Umpire is an open source Java program for computational analysis of data independent acquisition (DIA) mass spectrometry-based proteomics data. It enables untargeted peptide and protein identification and quantitation using DIA data, and also incorporates targeted extraction to reduce the number of cases of missing quantitation. 
  http://diaumpire.sourceforge.net/
name: dia_umpire
owner: galaxyp
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/dia_umpire
homepage_url: http://diaumpire.sourceforge.net/
type: unrestricted
