categories: [Proteomics]
description: ProteoRE Get expression data by tissue
long_description: A tool for finding tissue in which your proteins are expressed (or not) - Human Protein Atlas
name: proteore_get_expression_profiles
owner: proteore
include:
  - README.rst
  - get_expression_profiles.R
  - get_expression_profiles.xml
  - tool_data_table_conf.xml.sample
  - tool-data/proteinatlas.loc.sample
  - tool-data/HPA_normal_tissue_23-10-2018.tsv
  - tool-data/HPA_pathology_23-10-2018.tsv
  - test-data/ID_Converter_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/normal_tissue.tsv
  - test-data/pathology.tsv