categories: [Proteomics]
description: "give KEGG pathway(s) concerned by a given list of proteins or genes."
name: proteore_kegg_pathways_coverage
owner: proteore
include:
 - compute_kegg_pathways.xml
 - compute_kegg_pathways.R
 - test-data/SPZ.soluble.txt