categories: 
 - Proteomics
description: Discovers which phospho-substrates were found in common between multiple runs
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp
long_description: 'When a KALIP experiment is performed in multiple replicates, it can be useful to take only those highest confidence peptides into account by taking only peptides which were found in all three replicates
  '
name: commonality finder
owner: galaxyp
remote_repository_url: https://github.umn.edu/blank121/Commonality-and-difference-finder
