name: mt2mq
owner: galaxyp
description: Tool to prepare metatranscriptomic outputs from ASaiM for Metaquantome
long_description: |
    Tool to prepare metatranscriptomic outputs from ASaiM for Metaquantome
categories:
- Proteomics
