categories:
- Sequence Analysis
description: MetaGeneAnnotator gene-finding program for prokaryote and phage
long_description: |

  MetaGeneAnnotator (MGA) precisely predicts all kinds of 
  prokaryotic genes from a single or a set of anonymous 
  genomic sequences having a variety of lengths. 
  The MGA integrates statistical models of prophage genes, 
  in addition to those of bacterial and archaeal genes, 
  and also uses a self-training model from input sequences 
  for predictions. As a result, the MGA sensitively detects 
  not only typical genes but also atypical genes, such as 
  horizontally transferred and prophage genes in a 
  prokaryotic genome. 

  MetaGeneAnnotator results are used by sixgill to generate 
  metapeptides.

  http://metagene.cb.k.u-tokyo.ac.jp/

  doi: 10.1093/dnares/dsn027

name: metagene_annotator
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/metagene_annotator
type: unrestricted
homepage_url: http://metagene.nig.ac.jp/