categories: [Proteomics]
description: ProteoRE filter_keywords_values
long_description: Filter a file by keywords or values
name: filter_keywords_values
owner: proteore
include:
  - README.rst
  - filter_kw_val.py
  - filter_kw_val.xml
  - test-data/Lacombe_et_al_2017_OK.txt
  - test-data/FKW_Lacombe_et_al_2017_OK.txt
  - test-data/Trash_FKW_Lacombe_et_al_2017_OK.txt