categories: [Proteomics]
description: ProteoRE - Filter a file by keywords or values
long_description: Filter a file by keywords or values
name: proteore_filter_keywords_values
owner: proteore
include:
  - README.rst
  - filter_kw_val.py
  - filter_kw_val.xml
  - test-data/Lacombe_et_al_2017_OK.txt
  - test-data/output.csv
  - test-data/filtered_output.csv