owner: galaxyp
name: peptideshaker
categories:
- Proteomics
description: PeptideShaker and SearchGUI
long_description: |
  Runs multiple search engines (X! Tandem, OMSSA and MS-GF+) on any number of MGF peak lists using the SearchGUI application and combines the results.

  https://code.google.com/p/peptide-shaker/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/peptideshaker
homepage_url: http://compomics.github.io
type: unrestricted
