categories: [Proteomics]
description: Get unique peptide SRM-MRM method [SRM Atlas] 
name: proteore_get_unique_peptide_srm_method
owner: proteore
include:
- README.rst
- get_unique_srm.py
- proteore_get_unique_peptide_SRM-MRM_method.xml
- tool_data_table_conf.xml.sample
- tool_data_table_conf.xml.test
- test-data/Lacombe_et_al_2017_modified.tsv
- test-data/srm_results.tsv
- test-data/proteore_human_srm_atlas.loc
- tool-data/Human_SRM_atlas_2016-04.csv
- tool-data/proteore_human_srm_atlas.loc.sample
