categories: [Computational chemistry]
description: difference finder
homepage_url: https://pubs.acs.org/doi/abs/10.1021/ja507164a
long_description: This tool is intended for use in conjunction with KinaMine 7-7 and
  Kinatest 7-7.  This tool allows for the symmetrical difference to be taken between two sets
name: difference_finder
owner: galaxyp
remote_repository_url: https://github.umn.edu/blank121/Commonality-and-difference-finder