categories: [Tool Dependency Packages]
description: 'Tool dependencies for SearchGUI 1.27'
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_searchgui_1_27'
name: 'package_searchgui_1_27'
owner: 'iracooke'
