categories:
- Proteomics
description: APOSTL Workflows
long_description: |
  Workflows for APOSTL Paper

name: apostl
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/workflows/apostl
type: unrestricted
