categories: [Proteomics]
description: Extract MS/MS scans from the mzML file(s) based on PSM report.
long_description: |
    msms_extractor reads scan numbers from the PSM report (scan numbers with identified PSM) and gives option to create a new mzml file, either with those scans or without those scans.
    
    Input: mzML file and PSM report file
    Output: mzML file with scan numbers that were not assigned any PSM.
    
name: msms_extractor
owner: galaxyp
