categories:
- Proteomics
description: Download UniProt proteome in XML or fasta format
long_description: |
  Download UniProt proteome in XML or fasta format.  
  The Morpheus proteomics search engine uses the uniprotxml format.
  Uses the UniProt query API to retrieve entries for taxons.

  http://www.uniprot.org/help/programmatic_access
  http://www.uniprot.org/proteomes/

name: uniprotxml_downloader
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/uniprotxml_downloader
homepage_url: https://www.uniprot.org/help/programmatic_access
type: unrestricted

