categories: [Tool Dependency Packages]
description: 'Tool dependencies for SearchGUI 2.9'
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_searchgui_2_9'
name: 'package_searchgui_2_9'
owner: 'galaxyp'
