categories:
- Proteomics
description: De novo sequencing of tandem mass spectra
long_description: |
  The state of the art Deep CNN neural network for de novo sequencing of tandem
  mass spectra, currently works on unmodified HCD spectra of charges 1+ to 4+.
owner: galaxyp
name: pepnet
homepage_url: https://github.com/lkytal/PepNet
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/pepnet
type: unrestricted