categories:
    - Proteomics
description: The tool MzMLToMzLite allows to convert mzML files to mzLite files.
long_description: |
    The success of modern proteomics was made possible by constant progression in the field of mass spectrometry. 
    Over the course of the past years quite a few manufacturers of mass spectrometers have managed to establish themselfes in the field of biological research. 
    Since aquisition and accession of mass spectra are performance critical processes, various performance optimized, but vendor specific and closed source formats have been developed to store raw MS data. 
    This comes to the disadvantage for toolchain developers which want to provide tools for every scientist regardless of the format of their raw data.
name: proteomiqon_mzmltomzlite
owner: galaxyp
homepage_url: https://csbiology.github.io/ProteomIQon/tools/MzMLToMzLite.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteomIQon_MzMLToMzLite
type: unrestricted
