categories: [Proteomics]
description: map a list of Uniprot Accession number or Entrez gene ID to KEGG pathway
  with pathview R package
name: proteore_maps_visualization
owner: proteore
include:
 - kegg_maps_visualization.R
 - kegg_maps_visualization.xml
 - kegg_pathways_list_index.loc.sample
 - README.rst
 - tool_data_table_conf.xml.sample
 - test-data/hsa00010.pathview.png
 - test-data/hsa04514.pathview.png
 - test-data/hsa05167.pathview.png
 - test-data/Lacombe_et_al_2017_OK.txt
 - tool-data/hsa_pathways.loc
 - tool-data/mmu_pathways.loc
 - tool-data/rno_pathways.loc
 - tool-data/hsa_pathways.loc.sample
 - tool-data/mmu_pathways.loc.sample
 - tool-data/rno_pathways.loc.sample