categories: [Proteomics]
description: ProteoRE Add protein features
long_description: A tool for adding biochemical and cellular annotation to your protein list from neXtProt
name: proteore_prot_features
owner: proteore
include:
  - README.rst
  - add_protein_features.xml
  - add_protein_features.R
  - tool-data/result_nextprot.txt
  - test-data/FKW_ID_Converter_Lacombe_et_al_2017_OK.tsv
  - test-data/Add_information_from_neXtProt.tsv