categories: [Proteomics]
description: ProteoRE Add protein features
long_description: A tool for adding biochemical and cellular annotation to your protein list from neXtProt
name: proteore_prot_features
owner: proteore
include:
  - README.rst
  - add_protein_features.xml
  - add_protein_features.R
  - proteore_nextprot_ref.loc.sample
  - tool_data_table_conf.xml.sample
  - test-data/Lacombe_et_al_2017.tsv
  - test-data/Add_information_from_neXtProt.tsv
  - tool-data/nextprot_ref_09-03-2019.tsv
  - tool-data/nextprot_ref_08-10-2018.tsv
  - tool-data/nextprot_ref_07-05-2019.tsv