owner: galaxyp
name: msstitch
categories:
- Proteomics
description: MSStitch
long_description: |
  Post processing utilities for various MS formats, notably MSGF+ output, percolator output. Creating PSM, peptide and protein tables.

  https://github.com/glormph/msstitch
remote_repository_url: https://github.com/glormph/tools-galaxyp/tools/msstitch
type: unrestricted
