owner: galaxyp
name: msstitch
categories:
- Proteomics
description: MSStitch
long_description: |
  Post processing utilities for various MS ID/quant formats, notably MSGF+ output, percolator output. Creating PSM, peptide and protein tables.

  https://github.com/glormph/msstitch
remote_repository_url: https://github.com/glormph/tools-galaxyp/tools/msstitch
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the msstitch package"
suite:
  name: suite_msstitch
  description: msstitch performs postprocessing on a number of MS ID and quant formats to create usable combined output files
  type: repository_suite_definition

