categories: [Proteomics]
description: "give KEGG pathway(s) concerned by a given list of proteins or genes."
name: proteore_kegg_pathways_coverage
owner: proteore
include:
 - kegg_identification.xml
 - kegg_identification.R
 - test-data/SPZ.soluble.txt