categories: [Proteomics]
description: ProteoRE goProfiles
long_description: Statistical analysis of functional profiles
name: proteore_goprofiles
owner: proteore
include: 
  - README.rst
  - goprofiles.R
  - goprofiles.xml
  - test-data/ID_Converted_FKW_Lacombe_et_al_2017_OK.txt
  - test-data/GO_Profile_text_output.txt
  - test-data/profile.BP.pdf
  - test-data/profile.CC.pdf
  - test-data/profile.MF.pdf