name: rawtools
owner: galaxyp
categories: [Proteomics]
description: Raw Tools
long_description: package designed to perform scan data parsing and quantification,
  and quality control analysis of Thermo Orbitrap raw mass spectrometer files
homepage_url: https://github.com/kevinkovalchik/RawTools
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/rawtools
