owner: galaxyp
name: hirieftools
categories:
- Proteomics
description: HiRIEF tools
long_description: |
  High resolution isoelectric focusing is a prefractionation technique for shotgun proteomics/mass spectrometry in which peptides are focused along a pI gradient.
  These tools enable pI-based annotation and database preparation for HiRIEF experiments.
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/pi_db_tools
type: unrestricted
