categories: [Proteomics]
description: Compare lists of gene IDs with clusterProfiler R package (compareCluster function)
name: proteore_go_terms_enrich_comparison
owner: proteore
include:
  - GO_terms_enrich_comparison.R
  - GO_terms_enrich_comparison.xml
  - test-data/Gene_ID_BreastDn.txt  
  - test-data/Gene_ID_BreastUp.txt
  - test-data/GO_enrich_comparison_BP.png
  - test-data/GO_enrich_comparison_BP.tsv
