categories: [Proteomics]
description: Build an heatmap from an uto table
name: proteore_heatmap_visualization
owner: proteore
include:
  - heatmap_viz.R
  - heatmap.xml
  - test-data/heatmap.html
  - test-data/dat.nucl.norm.imputed.tsv