name: metaquantome
owner: galaxyp
description: quantitative analysis of microbiome taxonomy and function
long_description: metaQuantome provides tools for analysis of metaprotemic (community proteomic) data, leveraging quantitative information (like precursor intensity values), functional annotation, and taxonomic annotation.

remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/metaquantome
type: unrestricted
categories:
- Proteomics

auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "wrapper for {{tool_name}} module."

suite:
  name: "suite_metaquantome"
  description: metaQuantome suite for quantitative metaproteomic analysis
  long_description: metaQuantome provides tools for analysis of metaproteomic (community proteomic) data, leveraging quantitative information (like precursor intensity values), functional annotation, and taxonomic annotation.
