owner: galaxyp
name: metamorpheus
categories:
- Proteomics
description: MetaMorpheus MS Search Application
long_description: |
  MetaMorpheus is a bottom-up proteomics database search software 
  with integrated post-translational modification (PTM) discovery capability. 
  This application combines features of Morpheus and G-PTM-D in a single tool.

  Features automatic inclusion of known PTMs (Post Translational Modifications) 
  when a UniProt Proteome is used as the search database.

homepage_url: https://github.com/smith-chem-wisc/MetaMorpheus
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/metamorpheus
type: unrestricted
