categories:
- Genomic Interval Operations
- Proteomics
description: PepPointer categorizes peptides by their genomic coordinates. 
name: pep_pointer 
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/pep_pointer
type: unrestricted
