categories:
    - Proteomics
description: |
    Given raw an MS run in the mzLite format, this tool iterates across all MS/MS scans, determines precursor charge states and possible peptide spectrum matches using reimplementations of SEQUEST,
    Andromeda and XTandem.
long_description: |
    Given raw a MS run in the mzLite or mzml format, this tool iterates accross all recorded MS/MS scans and determines the charge state of precursor ions which were selected for fragmentation. 
    With this it is possible to query the peptide data base for every precursor ion mass +/- a tolerance (which defines the so called 'search space') and retrieve peptides that are theoretical candidates
    for a match. For each of the peptide candidates we create an theoretical spectrum in silico and compare it to the measured MS/MS scan.
name: proteomiqon_peptidespectrummatching
owner: galaxyp
homepage_url: https://csbiology.github.io/ProteomIQon/tools/PeptideSpectrumMatching.html
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/proteomiqon_peptidespectrummatching
type: unrestricted
