owner: galaxyp
name: eggnog_mapper
categories:
- Proteomics
description: eggnog-mapper fast functional annotation of novel sequences
long_description: |
  eggnog-mapper is a tool for fast functional annotation of novel sequences \
  (genes or proteins) using precomputed eggNOG-based orthology assignments

  https://github.com/jhcepas/eggnog-mapper
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/eggnog_mapper/eggnog_mapper
type: unrestricted
