categories: 
 - Proteomics
description: Centers and aligns all phospho-tyrosine containing peptides discovered by a mass spec
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp
long_description: 'In order to determine a kinase's preferred substrate motif, the peptides which is phosphorylates are extracted and aligned, centered on their phospho-tyrosine
  '
name: kinamine y for peptide shaker
owner: Johnbbbbb
remote_repository_url: https://github.umn.edu/blank121/kinamine-y-for-shaker