categories:
- Proteomics
description: Converts a BED file to a tabular list of exon locations
long_description: |

  Converts a BED file (12 column) to a 6 column tabular list of exon locations
  with columns: name,chrom,start,end,strand,cds_start,cds_end.  
  It relies on the ThickStart and ThckEnd columns of the BED file to define 
  the coding start and end of a protein sequence.

  The tabular format can be converted to a sqlite table for the quick lookup of
  the genomic location of any animo acid in the protein sequence.

name: bed_to_protein_map
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/bed_to_protein_map
type: unrestricted
