categories:
  - Proteomics
description: Enable protein summarisation and quantitation
long_description: |
    Enable protein summarisation and quantitation
name: lfq_protein_quant
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/lfq_protein_quant
homepage_url: https://github.com/compomics/LFQ_galaxy_p
type: unrestricted
