categories:
  - Data Managers
description: data manager to download and set necessary files for "Number of MS/MS
  observations in a tissue (from Peptide Atlas)" and "Get expression data by tissue
  finds tissue" from the proteore package
name: data_manager_proteore_peptide_atlas
owner: dchristiany
include: 
  - data_manager/resource_building.py  
  - data_manager/resource_building.xml
  - data_manager_conf.xml
  - tool_data_table_conf.xml.sample