categories: [Proteomics]
description: Compare lists of gene IDs with clusterProfiler R package (compareCluster function)
name: proteore_go_terms_profiles_comparison
owner: proteore
include:
  - GO_prof_comp.R
  - GO_prof_comp.xml
  - test-data/Bred.tsv  
  - test-data/Muc.tsv
  - test-data/GO_profiles_comp_BP.png  
  - test-data/GO_profiles_comp_BP.tsv  
  - test-data/log.txt  