categories: [Tool Dependency Packages]
description: 'Tool dependencies for PeptideShaker 1.10'
homepage_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages/package_peptideshaker_1_10'
name: 'package_peptideshaker_1_10'
owner: 'galaxyp'
