categories: [Proteomics]
description: ProteoRE Add expression data to your protein list (mRNA and protein level data from Human Protein Atlas)
name: proteore_expression_rnaseq_abbased
owner: proteore
include:
  - README.rst
  - get_data_HPA_v2.R
  - expression_rnaseq_abbased.xml
  - proteinatlas.csv
  - test-data/ID_Converter_Lacombe_et_al_2017_OK.txt
  - test-data/Get_annotation_RNAseq.txt