categories:
- Proteomics
description: Calgary approach to isotopes in proteomics
long_description: |
  Estimates isotopic composition (e.g. 13C/12C, delta13C, 15N/14N etc) of
  peptides from proteomics mass spectrometry data. Input data consist of mzML
  files and files with peptide spectrum matches.
owner: galaxyp
name: calisp
homepage_url: https://github.com/kinestetika/Calisp/
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tools/calisp
type: unrestricted