categories: 
 - Proteomics
description: Unipept retrieves metaproteomics information
homepage_url: https://github.com/galaxyproteomics/tools-galaxyp
long_description: 'Unipept retrieves taxonomy for tryptic peptides using the unipept API. 
  https://unipept.ugent.be
  https://unipept.ugent.be/apidocs 

  The Unipept metaproteomics analysis pipeline
  Bart Mesuere1,*, Griet Debyser2, Maarten Aerts3, Bart Devreese2, Peter Vandamme3 andPeter Dawyndt1
  Article first published online: 11 FEB 2015
  DOI: 10.1002/pmic.201400361
  '
name: unipept
owner: galaxyp
remote_repository_url: https://unipept.ugent.be/apidocs
