categories:
  - Proteomics
description: MSstatsTMT protein significance analysis in shotgun mass spectrometry-based proteomic experiments with tandem mass tag (TMT) labeling
name: msstatstmt
long_description: |
    MSstatsTMT provides statistical tools for detecting differentially abundant proteins in shot-gun mass spectrometry-based proteomic experiments with tandem mass tag (TMT) labeling.
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/msstatstmt
homepage_url: http://msstats.org/msstatstmt/
type: unrestricted
