categories: [Proteomics]
description: Number of MS/MS observations in a tissue (from Peptide Atlas)
name: proteore_ms_observation_pepatlas
owner: proteore
include:
  - proteore_ms_observation_pepatlas.R
  - proteore_ms_observation_pepatlas.xml
  - README.rst